In [1]:
# Import pandas library for data manipulation
import pandas as pd

# Quick check to confirm environment setup is working
print("Setup working!")

Setup working!

In [3]:
# Load the raw Superstore dataset using its full file path
df = pd.read_csv(r"C:\Users\Kirito\Documents\Data analysis project\retail-sales-analysis\Sample - Superstore.csv", encoding='latin1')

# Display first 5 rows to get an overview of the data structure
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
# Check data types and non-null counts for each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [5]:
# Check for missing values in each column
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [6]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [7]:
# Display column names and their data types
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [8]:
# Check current data type of Order Date column
print(df['Order Date'].dtype)
print(df['Order Date'].head())

str
0     11/8/2016
1     11/8/2016
2     6/12/2016
3    10/11/2015
4    10/11/2015
Name: Order Date, dtype: str

In [9]:
# Convert Order Date and Ship Date columns from string to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')

# Verify the conversion worked correctly
print(df['Order Date'].dtype)
df['Order Date'].head()

datetime64[us]

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[us]

In [10]:
# Standardize column names: remove spaces and convert to lowercase with underscores
# This makes column names easier to use in SQL queries later (e.g. Order_Date instead of "Order Date")
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Verify the new column names
print(df.columns.tolist())

['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State', 'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub-Category', 'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [12]:
import os

# Create the data/processed directory if it doesn't already exist
os.makedirs('../data/processed', exist_ok=True)

print("Directory created (or already exists)!")

Directory created (or already exists)!

In [13]:
# Save the cleaned dataset to a new CSV file for later use
df.to_csv('../data/processed/cleaned_superstore.csv', index=False)

print("Cleaned data saved successfully!")

Cleaned data saved successfully!

In [14]:
import sqlite3

# Create (or connect to) a SQLite database file inside data/processed folder
conn = sqlite3.connect('../data/processed/superstore.db')

# Write the cleaned DataFrame into a table named 'sales' inside the database
# if_exists='replace' ensures re-running this cell won't create duplicate tables
df.to_sql('sales', conn, if_exists='replace', index=False)

print("Data successfully written to SQLite database!")

Data successfully written to SQLite database!

In [15]:
# Quick test: read back a few rows from the database to confirm it worked
test_query = "SELECT * FROM sales LIMIT 5"
test_df = pd.read_sql(test_query, conn)
test_df

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [16]:
# Quick test: read back a few rows from the database to confirm it worked
test_query = "SELECT * FROM sales LIMIT 5"
test_df = pd.read_sql(test_query, conn)
test_df

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [17]:
# Query: Calculate total sales grouped by month
monthly_trend_query = """
SELECT strftime('%Y-%m', Order_Date) AS month, 
       SUM(Sales) AS total_sales,
       SUM(Profit) AS total_profit
FROM sales
GROUP BY month
ORDER BY month
"""

# Run the query and store result in a DataFrame
monthly_trend = pd.read_sql(monthly_trend_query, conn)
monthly_trend.head(10)

     month  total_sales  total_profit
0  2014-01   14236.8950     2450.1907
1  2014-02    4519.8920      862.3084
2  2014-03   55691.0090      498.7299
3  2014-04   28295.3450     3488.8352
4  2014-05   23648.2870     2738.7096
5  2014-06   34595.1276     4976.5244
6  2014-07   33946.3930     -841.4826
7  2014-08   27909.4685     5318.1050
8  2014-09   81777.3508     8328.0994
9  2014-10   31453.3930     3448.2573

In [18]:
# Query: Find the top 10 products by total sales amount
top_products_query = """
SELECT Product_Name, 
       SUM(Sales) AS total_sales,
       SUM(Quantity) AS total_quantity
FROM sales
GROUP BY Product_Name
ORDER BY total_sales DESC
LIMIT 10
"""

top_products = pd.read_sql(top_products_query, conn)
top_products

,Product_Name,total_sales,total_quantity
0,Canon imageCLASS 2200 Advanced Copier,61599.824,20
1,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384,31
2,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6
3,HON 5400 Series Task Chairs for Big and Tall,21870.576,39
4,GBC DocuBind TL300 Electric Binding System,19823.479,37
5,GBC Ibimaster 500 Manual ProClick Binding System,19024.500,48
6,Hewlett Packard LaserJet 3310 Copier,18839.686,38
7,HP Designjet T520 Inkjet Large Format Printer ...,18374.895,12
8,GBC DocuBind P400 Electric Binding System,17965.068,27
9,High Speed Automatic Electric Letter Opener,17030.312,11

In [19]:
# Query: Compare total sales and profit across regions
region_performance_query = """
SELECT Region, 
       SUM(Sales) AS total_sales, 
       SUM(Profit) AS total_profit,
       ROUND(SUM(Profit) * 100.0 / SUM(Sales), 2) AS profit_margin_pct
FROM sales
GROUP BY Region
ORDER BY total_profit DESC
"""

region_performance = pd.read_sql(region_performance_query, conn)
region_performance

    Region  total_sales  total_profit  profit_margin_pct
0     West  725457.8245   108418.4489              14.94
1     East  678781.2400    91522.7800              13.48
2    South  391721.9050    46749.4303              11.93
3  Central  501239.8908    39706.3625               7.92

In [20]:
# Query: Analyze profit margin by product category
category_breakdown_query = """
SELECT Category, 
       SUM(Sales) AS total_sales, 
       SUM(Profit) AS total_profit,
       ROUND(SUM(Profit) * 100.0 / SUM(Sales), 2) AS profit_margin_pct
FROM sales
GROUP BY Category
ORDER BY total_profit DESC
"""

category_breakdown = pd.read_sql(category_breakdown_query, conn)
category_breakdown

          Category  total_sales  total_profit  profit_margin_pct
0       Technology  836154.0330   145454.9481              17.40
1  Office Supplies  719047.0320   122490.8008              17.04
2        Furniture  741999.7953    18451.2728               2.49

In [21]:
# Query: Calculate total sales and profit grouped by month
monthly_trend_query = """
SELECT strftime('%Y-%m', Order_Date) AS month, 
       SUM(Sales) AS total_sales,
       SUM(Profit) AS total_profit
FROM sales
GROUP BY month
ORDER BY month
"""

monthly_trend = pd.read_sql(monthly_trend_query, conn)
monthly_trend.head(10)

     month  total_sales  total_profit
0  2014-01   14236.8950     2450.1907
1  2014-02    4519.8920      862.3084
2  2014-03   55691.0090      498.7299
3  2014-04   28295.3450     3488.8352
4  2014-05   23648.2870     2738.7096
5  2014-06   34595.1276     4976.5244
6  2014-07   33946.3930     -841.4826
7  2014-08   27909.4685     5318.1050
8  2014-09   81777.3508     8328.0994
9  2014-10   31453.3930     3448.2573

In [22]:
# Query: Find the top 10 products by total sales amount
top_products_query = """
SELECT Product_Name, 
       SUM(Sales) AS total_sales,
       SUM(Quantity) AS total_quantity
FROM sales
GROUP BY Product_Name
ORDER BY total_sales DESC
LIMIT 10
"""

top_products = pd.read_sql(top_products_query, conn)
top_products

,Product_Name,total_sales,total_quantity
0,Canon imageCLASS 2200 Advanced Copier,61599.824,20
1,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384,31
2,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6
3,HON 5400 Series Task Chairs for Big and Tall,21870.576,39
4,GBC DocuBind TL300 Electric Binding System,19823.479,37
5,GBC Ibimaster 500 Manual ProClick Binding System,19024.500,48
6,Hewlett Packard LaserJet 3310 Copier,18839.686,38
7,HP Designjet T520 Inkjet Large Format Printer ...,18374.895,12
8,GBC DocuBind P400 Electric Binding System,17965.068,27
9,High Speed Automatic Electric Letter Opener,17030.312,11

In [24]:
# Query: Compare total sales and profit across regions
region_performance_query = """
SELECT Region, 
       SUM(Sales) AS total_sales, 
       SUM(Profit) AS total_profit,
       ROUND(SUM(Profit) * 100.0 / SUM(Sales), 2) AS profit_margin_pct
FROM sales
GROUP BY Region
ORDER BY total_profit DESC
"""

region_performance = pd.read_sql(region_performance_query, conn)
region_performance

    Region  total_sales  total_profit  profit_margin_pct
0     West  725457.8245   108418.4489              14.94
1     East  678781.2400    91522.7800              13.48
2    South  391721.9050    46749.4303              11.93
3  Central  501239.8908    39706.3625               7.92

In [25]:
# Query: Analyze profit margin by product category
category_breakdown_query = """
SELECT Category, 
       SUM(Sales) AS total_sales, 
       SUM(Profit) AS total_profit,
       ROUND(SUM(Profit) * 100.0 / SUM(Sales), 2) AS profit_margin_pct
FROM sales
GROUP BY Category
ORDER BY total_profit DESC
"""

category_breakdown = pd.read_sql(category_breakdown_query, conn)
category_breakdown

          Category  total_sales  total_profit  profit_margin_pct
0       Technology  836154.0330   145454.9481              17.40
1  Office Supplies  719047.0320   122490.8008              17.04
2        Furniture  741999.7953    18451.2728               2.49